---
builds:
  - id: nri-prometheus
    main: ./cmd/nri-prometheus/
    binary: nri-prometheus
    ldflags:
      - -s -w -X github.com/newrelic/nri-prometheus/internal/integration.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - darwin
    hooks:
      pre: env MAJOR_MINOR_VERSION={{ .Major }}.{{ .Minor }} env PRE_RELEASE_VERSION={{ .Prerelease }} env FULL_VERSION={{ .Version }} go generate ./...
    ignore:
      - goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
dockers:
  - dockerfile: Dockerfile.release
    binaries:
      - nri-prometheus
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Major }}.{{ .Minor }}'
    skip_push: auto
  - dockerfile: Dockerfile.release
    binaries:
      - nri-prometheus
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
