builds:
  - id: nri-prometheus-nix
    main: ./cmd/nri-prometheus/
    binary: nri-prometheus
    ldflags:
      - -s -w -X github.com/newrelic/nri-prometheus/internal/integration.Version={{.Version}} #-X main.gitCommit={{.Commit}} -X main.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm

  - id: nri-prometheus-win
    main: ./cmd/nri-prometheus/
    binary: nri-prometheus
    ldflags:
      - -s -w -X github.com/newrelic/nri-prometheus/internal/integration.Version={{.Version}} #-X main.gitCommit={{.Commit}} -X main.buildDate={{.Date}}
    goos:
      - windows
    goarch:
      - 386
      - amd64
    hooks:
      pre: build/windows/set_exe_properties.sh {{ .Env.TAG }} "prometheus"

archives:
  - id: nri-prometheus-nix
    builds:
      - nri-prometheus-nix
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Version }}_{{ .Arch }}_dirty"
    format: tar.gz

  - id: nri-prometheus-win
    builds:
      - nri-prometheus-win
    name_template: "{{ .ProjectName }}-{{ .Arch }}.{{ .Version }}_dirty"
    format: zip

# we use custom publisher for fixing archives and signing them
release:
  disable: true

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    ids:
      - nri-prometheus-nix
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-amd64'
    use_buildx: true
    build_flag_templates:
    - "--platform=linux/amd64"
    skip_push: false
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile.release
    ids:
      - nri-prometheus-nix
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm64'
    use_buildx: true
    build_flag_templates:
    - "--platform=linux/arm64"
    skip_push: false
  - goos: linux
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile.release
    ids:
      - nri-prometheus-nix
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm'
    use_buildx: true
    build_flag_templates:
    - "--platform=linux/arm"
    skip_push: false

docker_manifests:
  - name_template: newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-amd64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm'
  - name_template: newrelic/nri-prometheus:{{ .Major }}.{{ .Minor }}{{ .Env.TAG_SUFFIX }}
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-amd64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm'
  - name_template: newrelic/nri-prometheus:latest{{ .Env.TAG_SUFFIX }}
    image_templates:
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-amd64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm64'
      - 'newrelic/nri-prometheus:{{ .Version }}{{ .Env.TAG_SUFFIX }}-arm'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
