FROM alpine:3.12

ARG BINARY=nri-prometheus

RUN apk add --no-cache --upgrade \
        ca-certificates

COPY ${BINARY} /bin/nri-prometheus

USER nobody

# When standalone is set to true nri-prometheus does not require an infrastructure agent to work and send data
ENV STANDALONE=TRUE

ENTRYPOINT ["/bin/nri-prometheus"]
