{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "nri-prometheus.fullname" . }}
  labels:
{{ include "nri-prometheus.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nri-prometheus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "nri-prometheus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
