{{- $licenseKey := include "nri-prometheus.licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nri-prometheus.labels" . | indent 4 }}
type: Opaque
data:
  licenseKey: {{ $licenseKey | b64enc }}
{{- end }}
