name: Security Scan
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.COREINT_SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
